Remove Prefect from codebase
It's currently all kinds of broken. Login to their cloud service
is failing (see previous commit), and there seems to have been
a change in their codebase leading to it pulling in a dependency
that doesn't exist:

```
Traceback (most recent call last):
  File "/home/runner/work/python_status_checker/python_status_checker/status_check.py", line 50, in <module>
    from prefect import flow, task, get_run_logger
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/prefect/__init__.py", line 45, in <module>
    from prefect.engine import pause_flow_run, resume_flow_run
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/prefect/engine.py", line 98, in <module>
    from anyio import start_blocking_portal
ImportError: cannot import name 'start_blocking_portal' from 'anyio' (/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/anyio/__init__.py)
Error: Process completed with exit code 1.
```